<?php
namespace CCC\Services;

defined('ABSPATH') || exit;

class PostTypeTemplateService {
    
    /**
     * Create a post type template file
     */
    public function createPostTypeTemplate($post_type, $components = []) {
        // Create templates directory in plugin instead of theme
        $templates_dir = plugin_dir_path(dirname(dirname(__FILE__))) . 'ccc-templates/post-types';
        
        if (!is_dir($templates_dir)) {
            wp_mkdir_p($templates_dir);
        }
        
        $template_file = $templates_dir . '/single-' . $post_type . '.php';
        
        // Generate template content
        $template_content = $this->generatePostTypeTemplateContent($post_type, $components);
        
        // Write template file
        $result = file_put_contents($template_file, $template_content);
        
        if ($result !== false) {
            error_log("CCC PostTypeTemplateService: Created post type template: $template_file");
            
            // Store component IDs for this post type
            $component_ids = [];
            foreach ($components as $component) {
                if (isset($component['id'])) {
                    $component_ids[] = $component['id'];
                }
            }
            update_option('_ccc_post_type_components_' . $post_type, $component_ids);
            
            return true;
        } else {
            error_log("CCC PostTypeTemplateService: Failed to create post type template: $template_file");
            return false;
        }
    }
    
    /**
     * Remove a post type template file
     */
    public function removePostTypeTemplate($post_type) {
        // Remove template from plugin directory
        $templates_dir = plugin_dir_path(dirname(dirname(__FILE__))) . 'ccc-templates/post-types';
        $template_file = $templates_dir . '/single-' . $post_type . '.php';
        
        if (file_exists($template_file)) {
            $result = unlink($template_file);
            if ($result) {
                error_log("CCC PostTypeTemplateService: Removed post type template: $template_file");
            } else {
                error_log("CCC PostTypeTemplateService: Failed to remove post type template: $template_file");
            }
        }
        
        // Clean up stored components
        delete_option('_ccc_post_type_components_' . $post_type);
        
        return true;
    }
    
    /**
     * Generate the content for a post type template file
     */
    private function generatePostTypeTemplateContent($post_type, $components = []) {
        $post_type_object = get_post_type_object($post_type);
        $post_type_label = $post_type_object ? $post_type_object->labels->singular_name : ucfirst(str_replace(['_', '-'], ' ', $post_type));
        
        $components_list = '';
        if (!empty($components)) {
            $components_list = "\n * Assigned Components:\n";
            foreach ($components as $component) {
                $components_list .= " * - " . $component['name'] . " (" . $component['handle_name'] . ")\n";
            }
        }
        
        return "<?php\n"
            . "/**\n"
            . " * Post Type Template: $post_type_label\n"
            . " * Post Type: $post_type\n"
            . " * \n"
            . " * This template is automatically generated by Custom Craft Component\n"
            . " * when components are assigned to this post type.\n"
            . " * \n"
            . " * You can customize this template to match your design needs.\n"
            . " * \n"
            . " * Template Hierarchy:\n"
            . " * 1. single-{post_type}.php (this file)\n"
            . " * 2. single.php\n"
            . " * 3. index.php\n"
            . $components_list
            . " */\n\n"
            . "// Prevent direct access\n"
            . "if (!defined('ABSPATH')) {\n"
            . "    exit;\n"
            . "}\n\n"
            . "// Enqueue CCC template styles\n"
            . "wp_enqueue_style('ccc-post-type-templates', plugins_url('inc/Views/post-type-templates.css', dirname(dirname(__FILE__))), [], '1.0.0');\n\n"
            . "get_header();\n\n"
            . "// Get the current post\n"
            . "\$post = get_post();\n"
            . "if (!\$post || \$post->post_type !== '$post_type') {\n"
            . "    wp_die('Invalid post type.');\n"
            . "}\n\n"
            . "// Debug logging\n"
            . "error_log('CCC Template: Post ID: ' . \$post->ID);\n\n"
            . "// Always render components for this post type (as requested by user)\n"
            . "if (function_exists('render_ccc_components')) {\n"
            . "    error_log('CCC Template: Calling render_ccc_components for post ID: ' . \$post->ID);\n"
            . "    render_ccc_components(\$post->ID);\n"
            . "    error_log('CCC Template: render_ccc_components completed');\n"
            . "} else {\n"
            . "    error_log('CCC Template: render_ccc_components function not found!');\n"
            . "    echo '<p>CCC Components function not available.</p>';\n"
            . "}\n\n"
            . "get_footer();\n";
    }
    
    /**
     * Create .htaccess file for URL rewriting
     */
    private function createHtaccessFile($templates_dir) {
        $htaccess_file = $templates_dir . '/.htaccess';
        if (!file_exists($htaccess_file)) {
            $htaccess_content = "RewriteEngine On\nRewriteBase /\n";
            file_put_contents($htaccess_file, $htaccess_content);
        }
    }
    
    /**
     * Create index.php file to prevent directory listing
     */
    private function createIndexFile($templates_dir) {
        $index_file = $templates_dir . '/index.php';
        if (!file_exists($index_file)) {
            $index_content = "<?php\n// Silence is golden.\n";
            file_put_contents($index_file, $index_content);
        }
    }
}
