<?php
/**
 * Post Type Template: Post
 * Post Type: post
 * 
 * This template is automatically generated by Custom Craft Component
 * when components are assigned to this post type.
 * 
 * You can customize this template to match your design needs.
 * 
 * Template Hierarchy:
 * 1. single-{post_type}.php (this file)
 * 2. single.php
 * 3. index.php
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Enqueue CCC template styles
wp_enqueue_style('ccc-post-type-templates', plugins_url('inc/Views/post-type-templates.css', dirname(dirname(__FILE__))), [], '1.0.0');

get_header();

// Get the current post
$post = get_post();
if (!$post || $post->post_type !== 'post') {
    wp_die('Invalid post type.');
}

// Debug logging
error_log('CCC Template: Post ID: ' . $post->ID);

// Always render components for this post type (as requested by user)
if (function_exists('render_ccc_components')) {
    error_log('CCC Template: Calling render_ccc_components for post ID: ' . $post->ID);
    render_ccc_components($post->ID);
    error_log('CCC Template: render_ccc_components completed');
} else {
    error_log('CCC Template: render_ccc_components function not found!');
    echo '<p>CCC Components function not available.</p>';
}

get_footer();
