name: Build Plugin

on:
  push:
    branches:
      - Master
    paths-ignore:
      - 'assets/**'
  workflow_dispatch:

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Update plugin version
        run: |
          # Read current version from main file
          CURRENT_VERSION=$(grep -oP "Version: \K[0-9.]+" ccc-plugin.php)
          
          # Update to new version
          NEW_VERSION="1.0.0.${{ steps.date.outputs.date }}"
          sed -i "s/Version: $CURRENT_VERSION/Version: $NEW_VERSION/" ccc-plugin.php
          sed -i "s/define( 'CCC_PLUGIN_VERSION', '$CURRENT_VERSION' );/define( 'CCC_PLUGIN_VERSION', '$NEW_VERSION' );/" ccc-plugin.php
          
          # Update version.json
          echo "{\"version\": \"$NEW_VERSION\", \"updated_at\": \"$(date +'%Y-%m-%d %H:%M:%S')\"}" > assets/version.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update plugin version to ${{ steps.date.outputs.date }}"
          git push origin Master